# manifest
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {MODEL_NAME}-deployment
spec:
  selector:
    matchLabels:
      app: {MODEL_NAME}-server
  replicas: 3
  template:
    metadata:
      labels:
        app: {MODEL_NAME}-server
    spec:
      containers:
        - name: {MODEL_NAME}-container
          image: docker.io/{DOCKER_USER}/{MODEL_NAME}:{github.sha}
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: {MODEL_NAME}-service
  name: {MODEL_NAME}-service
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: {MODEL_NAME}-server
  type: LoadBalancer
